language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^5[.][0-9]+$ ]]; then pecl install intl; fi
  - composer selfupdate
  - composer update --no-interaction --prefer-dist
  - composer require codeclimate/php-test-reporter:dev-master --dev

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=a95cd56eb76cc8e700a56d5f0b306ef7fc617873cfbf5ff07cda7f7e03437ec5 ./vendor/bin/test-reporter